name: Build and Release
on:
  push:
    branches:
      - ecs

jobs:
  build-and-release:
    uses: ixoworld/ixo-github-actions/.github/workflows/node-monorepo-ci-build.yml@main
    secrets: inherit
    with:
      testnet_branches_override: 'ecs'
    permissions:
      contents: write
      packages: write
      pull-requests: write
